### ISSUE TITLE
Simplify how to locate from which config the bug originates

### ISSUE THREAD

**Issue by francescoinfante** [Linkurious/linkurious-continuous-integration#12]
It's really hard at the moment to understand which configuration broke the run.
We have to scroll up by paying attention to not go to far, double-checking and so on.

**Comment by davidrapin** [comment]
solution : in the mocha exit code in case of error, we could print the vendor name of graph, index and db.

**Comment by francescoinfante** [comment]
Solved by running configs concurrently, only failing config will output #5
