### ISSUE TITLE
Installing custom npm does not work

### ISSUE THREAD

**Issue by davidrapin** [Linkurious/linkurious-continuous-integration#15]
install with ` -g` requires `sudo`.

> $ npm install -g npm@3.10.8
> npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm
> /usr/lib
> └── npm@3.10.8 
> 
> npm ERR! Linux 4.4.0-38-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "npm@3.10.8"
> npm ERR! node v6.8.0
> npm ERR! npm  v3.10.8
> npm ERR! path /usr/lib/node_modules/npm
> npm ERR! code EACCES
> npm ERR! errno -13
> npm ERR! syscall access

**Comment by francescoinfante** [comment]
Fixed
