### ISSUE TITLE
Move test/release scripts to respective projects

### ISSUE THREAD

**Issue by davidrapin** [Linkurious/linkurious-continuous-integration#23]
Currently, test scripts for the server is in `test_server.js` and for the client in `test_client.js`. We also have the release script in `release_lke.js`.

We should have some kind of  `echidna.json` file in each project that the CI is going to use to locate the test script , release script, and read configuration values.

Project config file
==
E.g.: server/echidna.json:
```
{
  "test": "scripts/echidnaTest.js",
  "release": "scripts/echidnaRelease.js",
  "cacheDependencies": true
}
```

Project script
==
The release scripts have a specific format: they export a function that receives a set of CI-specific objects as parameters.

E.g. "scripts/echidnaTest.js"
```
module.exports = function(ci, done) {
  // ci.options
  // ci.cla : parsed command line arguments 
  // ci.ciDirectory
  // ci.projectDirectory
  // ci.exec() (called with cwd:projectDirectory by default)
  // ci.dockerExec()
  // 
  // etc.
}
```

Usage
==
In the CI, setting up a new project is simply adding a "custom script" step and calling `./echidna release` in the "release step, `./echidna test` in the "test" step etc.
The ` echidna.js` script will take care of:
- reading command line arguments (e.g. `echidna test --build`)
- detecting the current project directory
- reading the configuration of the current project
- detecting if a script for the specified step ("test", "release", etc.) exists
- if a script for the step exists, run it

**Comment by francescoinfante** [comment]
To reinforce this issue:
When we develop a new DAO and we add it to the CI we forbid to any other branch to pass the CI.
So the actual configurations (docker_compose.yml files) have to be in the server folder

**Comment by francescoinfante** [comment]
An `echidnafile.js` is made of the following components:
- `name`
- `test`, script to test
- `build`, //
- `release`, //
- `buildDependencies`: array of github style projects (e.g: `'Linkurious/linkurious-client'`)
- `projectConcurrency`: max number of tests to run concurrently for the same repository

Things to be done from echidna:
- 1) create a new `workspace` directory where the repository is copied
- 2) parse `echidnafile.js` of the current project
- 4) run `test` of the current project
  - 1) each `test.js` file is a function that get as an argument an `echidna` object made of the following services:
    - **echidna.npm**
      - get(version) return the path to an npm binary of the given version (that is not going to change with concurrent runs) **note**: use `/usr/local/n/versions` or **`N_PREFIX`**
      - install(version, [path]) cached install of dependencies. **note**: access `node_modules` **read_only** since it's an hard link. **note 2**: path can be both folder or `package.json` file.
    - **echidna.node**
      - get(version) //
    - **echidna.bower**
      - install([path]) I won't bother with bower version
    - **echidna.utils**
      - exec(...), execAsync(...) etc. 

- 5) if `[build]` in commit message or `--build` or `--release` from cla
  - 1) run `build` of the `buildDependencies` (recursively without duplicates and trying to match the branch names)
  - 2) run `build` of the current project
  - **note**: each dependencies will be cloned and build in the same flat workspace. The workspace is a randomly generated (or current date) folder to allow concurrency. The workspace folder allows for `build` scripts to read and copy files among dependencies to actually build stuff. 
  - **use case**: `linkurious-server` to build requires to be in a folder along with `linkurious-client`
- 6) if `--release` from cla run `release` of the current project
- 7) if `test` occurred, everything put in the ad hoc folder of the workspace: `testOutput` will be copied to the dev machine in the folder `data/${name}/testResults/${current_date + name + branch name + nameDep1 + branch nameDep1 etc}`
  - **use case** code coverages, logs
- 8)  if `build` occurred, everything put in the ad hoc folder of the workspace: `buildOutput` will be copied to the dev machine in the folder `data/${name}/builds/${current_date + name + branch name + nameDep1 + branch nameDep1 etc}`
  - **use case** builds for seb

- [ ] Put in this also #19 and #21

**Comment by francescoinfante** [comment]
i don't see a way to abstract docker in `echidna.js`. Imho it's going to be handled completely by the test server script
