### ISSUE TITLE
Launch a test with the Starter edition

### ISSUE THREAD

**Issue by davidrapin** [Linkurious/linkurious-continuous-integration#24]
`node ./test/runMocha --starter`

**Comment by francescoinfante** [comment]
Neo4j configuration is run in starter mode

**Comment by davidrapin** [comment]
is the neo4j config also run in enterprise mode?

**Comment by francescoinfante** [comment]
at the moment no,
Yeah neo4j is a poor decision to run it in starter mode since is the only one testing alerts lol
neo4j will run twice then

**Comment by davidrapin** [comment]
ok

David Rapin
CTO & co-founder
http://linkurio.us
