### ISSUE TITLE
render console output colors in HTML interface

### ISSUE THREAD

**Issue by davidrapin** [Linkurious/linkurious-continuous-integration#3]
https://www.npmjs.com/package/ansi-to-html seems to be a good bet, can we make a PR to Strider to fix this?
- [ ] report issue, create PR to StriderCD

**Comment by francescoinfante** [comment]
The issue occurs only when looking at completed jobs.

Edit: Completed jobs with a really long output (~2000 lines).

**Comment by davidrapin** [comment]
caused by https://github.com/Strider-CD/strider/issues/999

**Comment by francescoinfante** [comment]
what's left to do?

**Comment by francescoinfante** [comment]
Solved by modifying strider code directly. (I was getting annoyed that I couldn't read error sometimes)
No need to fork strider, I just increased the limit
