### ISSUE TITLE
Add MSSQL to the CI with SQL-server for linux

### ISSUE THREAD

**Issue by francescoinfante** [Linkurious/linkurious-continuous-integration#9]
We can't run windows in docker under linux so:
https://helabs.com/artigos/2014/09/19/mssql-on-vagrant/

**Comment by davidrapin** [comment]
Actually there is a version of SQL-server for Linux available in beta: https://www.microsoft.com/en-us/sql-server/sql-server-vnext-including-Linux

**Comment by francescoinfante** [comment]
Oct 12 wasn't public lol, ok let's test it with this

**Comment by francescoinfante** [comment]
done
